In [15]:
import torch
import torch.nn as nn
from models import block_models

inn = torch.randn((5, 2, 3))

bn = nn.BatchNorm1d(2)

bn(inn)

tensor([[[ 0.0711, -1.2581, -2.2294],
         [ 0.8114, -1.4568,  0.4071]],

        [[ 0.2359,  0.4313,  0.1351],
         [-0.5697,  0.0578,  1.4971]],

        [[ 0.9583,  1.3785, -1.2567],
         [-1.5160,  0.6019, -1.4255]],

        [[-1.3029,  0.2886,  0.1156],
         [-0.6235, -0.3993, -0.6774]],

        [[ 0.7331,  0.7868,  0.9127],
         [ 0.9560,  1.4331,  0.9037]]], grad_fn=<NativeBatchNormBackward0>)

In [16]:
cha = [1]

print(cha[1:])

[]


In [10]:
from models.block_models import FeatureEncoder
import torch
import torch.nn as nn

seed = 1234

Nprod_Veclen = 2

Len_prodFeature = 3

Len_customerFeature = 4

torch.manual_seed(seed)

data = torch.randn((10, 4+3*2))

model = FeatureEncoder(
    seed,
    Nprod_Veclen,

    prod_normalize = False,
    Len_prodFeature = Len_prodFeature,
    cus_normalize = False,
    Len_customerFeature = Len_customerFeature,

    Num_cusEncoder_midLayer = 0,
    cusEncoder_midLayers = [],

    Num_prodEncoder_midLayer = 1,
    prodEncoder_midLayers = [4],

    CROSS = False
)

model(data)

tensor([[-0.3614, -0.8226],
        [-0.3024, -0.9585],
        [ 1.1052,  0.9855],
        [ 0.0257,  2.3367],
        [ 0.0045, -1.0837],
        [-2.6662,  1.2738],
        [ 0.9651,  0.6077],
        [ 0.1596,  1.0136],
        [ 0.2307,  0.0642],
        [-0.0453, -0.1894]], grad_fn=<SqueezeBackward1>)

In [3]:
import numpy as np

SAMP = np.load("EXP1_datasets/MNL/NProd_20/SAMP.npy")

print(SAMP[:5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
import torch

utils = torch.nn.Parameter(
            torch.randn(9,requires_grad=True)
        )
utils = torch.cat((torch.Tensor([0]), utils),0)
utils

tensor([ 0.0000,  0.8456,  1.4565,  0.4066, -0.9106,  1.6293, -1.3852, -1.6899,
        -0.8531, -0.8009], grad_fn=<CatBackward0>)

In [2]:
import numpy as np

M = np.load("EXP1_datasets/MC/NProd_20/M.npy")
print(np.sum(M[5:10], axis=0))

[0.01583723 0.00884238 0.04774807 0.12396453 0.00301629 0.68932549
 1.60252876 0.67627213 0.32621064 0.90875258 0.00769454 0.00208655
 0.00162293 0.07549914 0.10014278 0.14091648 0.02166428 0.02257717
 0.02144915 0.20384889]


In [4]:
lam = np.load("EXP1_datasets/MC/NProd_20/Lam.npy")
print(lam)

[1.54376617e-01 1.09706388e-01 6.85707954e-03 2.21304812e-02
 2.22739562e-02 1.54376617e-01 8.50978012e-04 3.94264023e-02
 1.28288536e-03 3.05809052e-03 1.54376617e-01 6.20428454e-03
 2.85530963e-02 3.35337224e-03 9.31333522e-05 1.54376617e-01
 4.41405486e-02 2.52680877e-03 9.17561683e-02 2.79858877e-04]


In [4]:
import numpy as np

np.random.choice(4)

2